config/routes.rb
Rails.application.routes.draw do
  resources :plants
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/plant.rb
class Plant < ApplicationRecord
	validates :name, :price, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: %i[ show edit update destroy ]

  # GET /plants or /plants.json
  def index
    @plants = Plant.all
  end

  # GET /plants/1 or /plants/1.json
  def show
  end

  # GET /plants/new
  def new
    @plant = Plant.new
  end

  # GET /plants/1/edit
  def edit
  end

  # POST /plants or /plants.json
  def create
    @plant = Plant.new(plant_params)

    respond_to do |format|
      if @plant.save
        format.html { redirect_to plant_url(@plant), notice: "Plant was successfully created." }
        format.json { render :show, status: :created, location: @plant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plants/1 or /plants/1.json
  def update
    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to plant_url(@plant), notice: "Plant was successfully updated." }
        format.json { render :show, status: :ok, location: @plant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1 or /plants/1.json
  def destroy
    @plant.destroy

    respond_to do |format|
      format.html { redirect_to plants_url, notice: "Plant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plant
      @plant = Plant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plant_params
      params.require(:plant).permit(:name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsNewTestProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/plants/_form.html.erb
<%= form_with(model: plant) do |form| %>
  <% if plant.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

      <ul>
        <% plant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: 'form-control form-control-lg' %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price, class: 'form-control form-control-lg' %>
  </div>

  <div class="form-group mt-3">
    <%= form.submit class: "btn btn-primary btn-lg" %>
    <%= link_to "Back to plants", plants_path, class: "btn btn-outline-primary btn-lg" %>

  </div>
<% end %>

app/views/plants/_plant.html.erb
<div id="<%= dom_id plant %>">
  <p>
    <strong>Name:</strong>
    <%= plant.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= plant.price %>
  </p>

</div>

app/views/plants/edit.html.erb
<div class="col-lg-8 mx-auto">
  <div class="card shadow">
    <div class="card-header">
      <h1 class="card-title">Edit plant</h1>
    </div>
    <div class="card-body">
      <%= render "form", plant: @plant %>
    </div>
  </div>
</div>

app/views/plants/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="col-lg-8 mx-auto">
  <h1>Plants</h1>
  <%= link_to "New plant", new_plant_path, class: "btn btn-primary btn-lg mb-3" %>
  <div id="plants">
    <% @plants.each do |plant| %>
      <div class="card shadow mb-3">
        <div class="card-body">
          <%= render plant %>
          <p>
            <%= link_to "Show this plant", plant, class: "btn btn-primary" %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/plants/new.html.erb
<div class="col-lg-8 mx-auto">
  <div class="card shadow">
    <div class="card-header">
      <h1 class="card-title">New plant</h1>
    </div>
    <div class="card-body">
      <%= render "form", plant: @plant %>
    </div>
  </div>
</div>

app/views/plants/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="col-lg-8">
  <div class="card shadow">
    <div class="card-body">
      <%= render @plant %>
    </div>
  </div>
  <div class="mt-4">
    <%= link_to "Edit this plant", edit_plant_path(@plant), class: "btn btn-warning" %> 
    <%= link_to "Back to plants", plants_path, class: "btn btn-outline-primary" %>

    <%= button_to "Destroy this plant", @plant, method: :delete, class: "btn btn-danger mt-2" %>
  </div>
</div>